apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-scraper
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: {{ .Values.cronjob.image }}
              command: ["yarn", "scraper"]
          restartPolicy: OnFailure
