apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-scraper
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              command: ["yarn", "scraper", "&&", "yarn", "search:learn"]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.api.env.databaseSecret.name }}
                      key: {{ .Values.api.env.databaseSecret.key }}
                - name: MAILGUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.api.env.mailgunSecret.name }}
                      key: {{ .Values.api.env.mailgunSecret.key }}
                - name: MAILGUN_DOMAIN
                  value: {{ .Values.api.env.mailgunDomain }}
                - name: MAILGUN_SENDER_EMAIL
                  value: {{ .Values.api.env.mailgunSenderEmail }}
                - name: OPENAI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.api.env.openAiSecret.name }}
                      key: {{ .Values.api.env.openAiSecret.key }}
                - name: NODE_ENV
                  value: production
          restartPolicy: OnFailure
