name: Deploy Helm Chart

on:
  workflow_run:
    workflows: ["Build and Push to GHCR"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with DigitalOcean using doctl
      - name: Authenticate with DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Set up Kubernetes context
      - name: Set up Kubernetes context
        run: |
          doctl kubernetes cluster kubeconfig save leser-digital-prod-cluster

      # Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      # Deploy Helm chart
      - name: Deploy Helm Chart
        env:
          NAMESPACE: production
          RELEASE_NAME: leser-digital-backend-prod
        run: |
          bash deployment/scripts/deploy.sh
      # Trigger frontend redeployment on DigitalOcean App Platform
      - name: Trigger Frontend Redeployment
        run: |
          doctl apps create-deployment 50ff4c4f-20b1-4ae2-a4ba-76fce223f86a